name: Publish Update

on: 
  push:
    branches:
      - master
      - github-actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm i
      
    - name: npm install gulp
      run: | 
        npm i -g gulp gulp-cli
        gulp --version
      
    - name: tslint check
      run: gulp tslint
      
    - name: typescript compile
      run: gulp tsc
      
    - name: typescript compile V1 code
      run: gulp tscV1
    
    
    - name: Publish to npm
      run: npm publish
      env:
        NPM_AUTH_TOKEN: d91b08fb-3479-4995-8c6d-7c5b205c60a4
     
    
        
