name: Node CI

on: 
  push:
    branches:
      - master
      - github-actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install    
      run: npm i
      
    - name: npm install gulp
      run: npm i -g gulp gulp-cli
    
    - name: run pre deploy
      run: gulp preDeploy
    
    - name: increment patch version
      run: gulp updatePatch
    
    - name: npm publish
      run: npm publish 
     
    
        
